### ISSUE TITLE
MegaFuse "fails", armv7, Ubuntu 15.04

### ISSUE THREAD

**Issue by devizer** [matteoserva/MegaFuse#56]
```
sudo apt-get install -y libcrypto++-dev libdb5.3++-dev libcurl4-openssl-dev libfreeimage-dev libreadline-dev libfuse-dev make

mkdir -p ~/src/megafuse && cd ~/src/megafuse
git clone https://github.com/matteoserva/MegaFuse
cd MegaFuse
make
sudo make install

root@OrangePI ~/src/megafuse/MegaFuse $ sudo MegaFuse -c ~/.megafuse.conf
ss /root/.megafuse.conf
caricata la variabile USERNAME con il valore annivation@gmail.com
caricata la variabile PASSWORD con il valore Ryb;ysq
caricata la variabile MOUNTPOINT con il valore /mega
caricata la variabile CACHEPATH con il valore /cache
MegaFushe::MegaFuse. Constructor finished.
searching node by path: /.megafuse_symlink
root@OrangePI ~/src/megafuse/MegaFuse $ cat ~/.megafuse.conf
USERNAME = **********
PASSWORD = *****
MOUNTPOINT = /mega
CACHEPATH = /cache
```

The same installer on i386 works fine with the same .conf

**Comment by quang4ngo** [comment]
I get a crash on an ARM ODROID:
```
Reading symbols from MegaFuse...done.
(gdb) run
Starting program: /root/MegaFuse-master/MegaFuse
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Cannot access memory at address 0x0

Program received signal SIGILL, Illegal instruction.
0xb64a8268 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
(gdb) where
#0  0xb64a8268 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
#1  0xb64a5f10 in OPENSSL_cpuid_setup () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
#2  0xb6fea19e in call_init (l=<optimized out>, argc=1, argv=0xbefff694, env=0xbefff69c) at dl-init.c:78
#3  0xb6fea230 in _dl_init (main_map=0xb6fff958, argc=1, argv=0xbefff694, env=0xbefff69c) at dl-init.c:126
#4  0xb6fdfbf2 in _dl_start_user () from /lib/ld-linux-armhf.so.3
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) f 1
#1  0xb64a5f10 in OPENSSL_cpuid_setup () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
(gdb) q
```

**Comment by devizer** [comment]
By the way, MegaFuse works fine with builtin g++ and libs from official debian 7 repo at PowerPC big-endian apple G3. 

So, what the hall with armv7? IS it only my problem?
